spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: 'jdbc:h2:mem:mydb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1'
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2

currency:
  scheduler:
    cron: "*/20 * * * * *"